channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=22.2.2
- pip:
  - mlflow
  - cffi==1.15.1
  - defusedxml==0.7.1
  - ipython==8.5.0
  - matplotlib==3.5.3
  - psutil==5.9.2
  - shap==0.41.0
  - typing-extensions==4.3.0
name: mlflow-env
